#!/bin/bash

cat << 'INNER_EOF' >> ~/.bashrc

# Custom Aliases
alias upgrade='sudo apt update && sudo apt upgrade -y'
alias resync='source ~/.bashrc'
alias submenu='nano ~/.bashrc'
alias new='konsole &'
alias hi='echo hello && sleep 2 && echo what command do you want to preform'
alias bye='echo bye closing in 5 secs  &&  sleep 5 && exit'
# Help Command
alias helpfetch='Subcommands:submenu bye hi resync upgrade and new

# --- THE ULTIMATE WINDOWS HELP ---
alias winhelper="echo google it linux breaks due to to much cmds in help'
# --- THE COMPLETE MEGA-COMMANDER (STABLE & FULL) ---

alias ren='mv'
alias del='rm -v'
alias erase='rm -v'
alias type='cat'
alias md='mkdir -p'
alias rd='rm -rf'
alias attrib='chmod'
alias chkdsk='sudo fsck'
alias scandisk='sudo fsck'
alias diskpart='sudo fdisk'
alias defrag='sudo fstrim -av'
alias vol='df -h'
alias mountvol='lsblk'
alias label='e2label'
alias fsutil='tune2fs'
alias compact='tar -czvf'
alias expand='unzip'
alias recover='testdisk'
alias ftype='xdg-mime query default'
alias assoc='xdg-mime query default'
alias where='which'
alias comp='diff'
alias fc='diff -u'
alias cls='clear && printf "\033c"'
alias "cd.."='cd ..'
alias "cd..."='cd ../..'
alias cdroot='cd /'

alias start='xdg-open'
alias runas='sudo'
alias exit='exit'
alias title='echo -ne "\033]0;$1\007"'
alias color='echo "Use Konsole Settings"'
alias pause='read -p "Press [Enter] to continue..." '
alias timeout='sleep'
alias choice='read -n 1 -p'
alias rem='#'

alias call='source'
alias cmd='bash'
alias ver='lsb_release -a'
alias tasklist='ps -aux'
alias taskmgr='ksysguard'
alias qprocess='ps'
alias query='ps'
alias taskkill='killall'
alias tskill='killall'
alias perfmon='htop'
alias resmon='btop'
alias msinfo32='sudo dmidecode'
alias systeminfo='fastfetch'
alias dxdiag='glxinfo'
alias driverquery='lsmod'
alias powercfg='upower -i /org/freedesktop/UPower/devices/battery_BAT0'
alias sc='sudo systemctl'
alias shutdown='shutdown now'
alias reboot='reboot'
alias logoff='logout'
alias eventvwr='journalctl'
alias wevtutil='journalctl'
alias logman='journalctl'
alias sfc='sudo apt install --reinstall'
alias DISM='sudo apt update && sudo apt full-upgrade'
alias cleanmgr='sudo apt autoremove'
alias bootrec='sudo update-grub'
alias bcdedit='nano /etc/default/grub'
alias nslookup='nslookup'
alias netstat='ss -tulpn'
alias nbtstat='nmblookup'
alias route='ip route'
alias arp='arp -a'
alias getmac='ip link show'
alias hostname='hostname'
alias tracert='traceroute'
alias pathping='mtr'
alias finger='finger'
alias whois='whois'
alias nsh='nmcli'
alias netsh='nmcli'
alias Get-Process='ps -aux'
alias Stop-Process='kill'
alias Get-Service='systemctl list-units --type=service'
alias Get-Content='cat'
alias Set-Location='cd'
alias Move-Item='mv'
alias Copy-Item='cp'
alias Remove-Item='rm'
alias New-Item='touch'
alias Test-Path='test -e'
alias Get-History='history'
alias Get-Date='date'
alias Get-Alias='alias'
alias Write-Host='echo'
alias Read-Host='read'
alias Start-Sleep='sleep'
alias Measure-Command='time'
alias gci='ls -alh'
alias findstr='grep'
alias find='grep'

alias more='less'
alias print='lp'
alias clip='xclip -selection clipboard'
alias cipher='shred -vz'
alias bitlocker='cryptsetup'
alias manage-bde='cryptsetup'
alias certutil='openssl'
alias certreq='openssl req'
alias kinit='kinit'
alias klist='klist'
# --- THE WINDOWS STYLE HELP ---
# This alias is now your ONLY help command
alias winhelp=" echo 'Microsoft Windows [Version 10.0.19045]'; echo '(c) Microsoft Corporation. All rights reserved.'; echo ''; echo 'ATTRIB      - Change file attributes'; echo 'CLS         - Clear screen'
INNER_EOF

# Startup Fetch
fastfetch --logo-color-1 \"#8b0000\"  --color-keys \"#8b0000\"
